spring:
  application:
    name: spring-ai-project

  ai:
    ollama:
      base-url: http://localhost:11434   #  correct port
      chat:
        options:
          model: deepseek-coder-v2:latest         # or deepseek-coder-v2:latest
          temperature: 0.7

server:
  port: 8081